### ISSUE TITLE
set/get controls

### ISSUE THREAD

**Issue by kayabe** [lineage-rpi/android_external_v4l-utils#1]
when trying to get or set controls `v4l2-ctl` just crashes saying `Segmentation fault`

i would've tried fixing this myself but i cant figure out how to compile this

**Comment by KonstaT** [comment]
Yes, I can reproduce this but I haven't looked into it.

This is built as part of AOSP(-based) source code. Clone this repository to external/v4l-utils or add it to your manifest.

You can use some arm64 target to compile.

device.mk:
```
# V4L utils
PRODUCT_PACKAGES += \
    cec-ctl \
    ir-keytable \
    v4l2-ctl
```

To compile:
```
. build/envsetup.sh
lunch {build_target}
make cec-ctl ir-keytable v4l2-ctl -jX
```

If you don't want to download the whole Android source code you can probably also use Android NDK to compile this but you'd need to figure that out.

**Comment by kayabe** [comment]
alright i have managed to compile it thanks to your guiding, i will try to figure out whats causing it to crash

**Comment by kayabe** [comment]
it seems to have been fixed in this commit:
https://git.linuxtv.org/v4l-utils.git/commit/?id=6e19bb895a16a9a247524ac526ab47f576cc36f6

but it gave me an error that was fixed by modifying v4l-getsubopt.h accordingly:
```
-  switch (sizeof (longword))
-    {
-    case 4: magic_bits = 0x7efefeffL; break;
-    case 8: magic_bits = ((0x7efefefeL << 16) << 16) | 0xfefefeffL; break;
-    default:
-      abort ();
-    }
+  magic_bits = -1;
+  magic_bits = magic_bits / 0xff * 0xfe << 1 >> 1 | 1;
```

would it be possible for you to add that commit here?

**Comment by KonstaT** [comment]
Thank you. :) I've pushed the commit. Didn't come across any issue building it so didn't need your fix.

Apparently there's no controls available when using unicam driver for the Pi camera modules like there is when using MMAL (or external USB webcams). Played around with some controls and it seems to work fine.

Closing as this should be resolved.

**Comment by kayabe** [comment]
this is what i get when i try to compile with `make v4l2-ctl -j16`:
```
external/v4l-utils/utils/v4l2-ctl/../../include/v4l-getsubopt.h:82:40: error: signed shift result (0x7EFEFEFE0000) requires 48 bits to represent, but 'long' only has 32 bits [-Werror,-Wshift-overflow]
    case 8: magic_bits = ((0x7efefefeL << 16) << 16) | 0xfefefeffL; break;
                           ~~~~~~~~~~~ ^  ~~
1 error generated.
```
maybe its because i'm doing this with docker?
also that fix i found it here: https://github.com/chino-os/chino-toolchain/blob/chino/packages/glibc-linaro/2.20-2014.11/0002-fix-signed-shift-overlow.patch

```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by KonstaT** [comment]
IDK. Could be, but seems strange build environment would effect this. Android build uses its own clang/gcc, not the host one.

Good to have the fix documented here anyway in case anyone needs it later.
